####### Aliases #######

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias clr='clear'
alias cls='clear'
alias dir='pwd -LP'
alias egrep='egrep --color=auto'
alias exit='exit 0'
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gaa='git add .'
alias gaaa='git add -A'
alias gb='git branch'
alias gc='git checkout'
alias gcm='git commit -m'
alias gd='git diff'
alias gl='git log'
alias gp='git pull'
alias gpsh='git push'
alias gpshup='git push --set-upstream upstream master'
alias grep='grep --color=auto'
alias grh='git reset --hard'
alias grm='git rm --cached'
alias grs='git reset --soft'
alias gs='echo ""; echo "*********************************************"; echo -e "   DO NOT FORGET TO PULL BEFORE COMMITTING"; echo "*********************************************"; echo ""; git status'
alias gset='gsettings'
alias gss='git status -s'
alias hostname='hostnamectl'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias nf='neofetch'
alias py='python3'
alias python='python3'
alias rl='. ~/.bash_aliases'
alias rm='trash'
alias x='exit'
